create table car (
	id INT,
	make VARCHAR(50),
	model VARCHAR(50),
	price VARCHAR(50)
);
insert into car (id, make, model, price) values (1, 'Honda', 'Crosstour', '$7.14');
insert into car (id, make, model, price) values (2, 'Subaru', 'Impreza', '$9.68');
insert into car (id, make, model, price) values (3, 'Chevrolet', 'Silverado 1500', '$1.32');
insert into car (id, make, model, price) values (4, 'Nissan', 'Sentra', '$0.69');
insert into car (id, make, model, price) values (5, 'Dodge', 'Ram 2500', '$7.29');
insert into car (id, make, model, price) values (6, 'Ford', 'Crown Victoria', '$3.54');
insert into car (id, make, model, price) values (7, 'Dodge', 'Ram 1500', '$0.71');
insert into car (id, make, model, price) values (8, 'Cadillac', 'Eldorado', '$8.03');
insert into car (id, make, model, price) values (9, 'Chrysler', 'Pacifica', '$0.57');
insert into car (id, make, model, price) values (10, 'Dodge', 'Dakota', '$4.26');
insert into car (id, make, model, price) values (11, 'Lotus', 'Esprit', '$0.73');
insert into car (id, make, model, price) values (12, 'Honda', 'Civic', '$8.84');
insert into car (id, make, model, price) values (13, 'Chevrolet', 'Camaro', '$9.48');
insert into car (id, make, model, price) values (14, 'Pontiac', 'Trans Sport', '$2.92');
insert into car (id, make, model, price) values (15, 'Mazda', 'Familia', '$2.61');
insert into car (id, make, model, price) values (16, 'Chevrolet', 'Camaro', '$3.03');
insert into car (id, make, model, price) values (17, 'GMC', 'Rally Wagon 2500', '$9.90');
insert into car (id, make, model, price) values (18, 'Mercedes-Benz', 'S-Class', '$2.24');
insert into car (id, make, model, price) values (19, 'Ford', 'F350', '$4.60');
insert into car (id, make, model, price) values (20, 'Audi', 'A8', '$1.46');
insert into car (id, make, model, price) values (21, 'Mazda', 'CX-5', '$1.79');
insert into car (id, make, model, price) values (22, 'Nissan', 'Xterra', '$4.87');
insert into car (id, make, model, price) values (23, 'Mitsubishi', 'Diamante', '$0.85');
insert into car (id, make, model, price) values (24, 'Acura', 'RSX', '$9.34');
insert into car (id, make, model, price) values (25, 'Audi', 'TT', '$2.75');
insert into car (id, make, model, price) values (26, 'Mercury', 'Cougar', '$2.23');
insert into car (id, make, model, price) values (27, 'Jeep', 'Wrangler', '$9.29');
insert into car (id, make, model, price) values (28, 'Mazda', 'B-Series', '$3.10');
insert into car (id, make, model, price) values (29, 'Jaguar', 'S-Type', '$6.29');
insert into car (id, make, model, price) values (30, 'Plymouth', 'Prowler', '$1.90');
insert into car (id, make, model, price) values (31, 'Volkswagen', 'Touareg 2', '$9.99');
insert into car (id, make, model, price) values (32, 'Lexus', 'IS-F', '$5.88');
insert into car (id, make, model, price) values (33, 'Mercury', 'Villager', '$8.74');
insert into car (id, make, model, price) values (34, 'Mercury', 'Tracer', '$2.80');
insert into car (id, make, model, price) values (35, 'Hyundai', 'Tiburon', '$9.96');
insert into car (id, make, model, price) values (36, 'Subaru', 'Impreza', '$4.80');
insert into car (id, make, model, price) values (37, 'Dodge', 'Dakota Club', '$8.53');
insert into car (id, make, model, price) values (38, 'Buick', 'Park Avenue', '$3.24');
insert into car (id, make, model, price) values (39, 'Cadillac', 'Escalade EXT', '$2.58');
insert into car (id, make, model, price) values (40, 'Chevrolet', '2500', '$9.21');
insert into car (id, make, model, price) values (41, 'Lotus', 'Esprit', '$4.96');
insert into car (id, make, model, price) values (42, 'Audi', 'A8', '$9.81');
insert into car (id, make, model, price) values (43, 'Subaru', 'Legacy', '$0.01');
insert into car (id, make, model, price) values (44, 'Volvo', 'S90', '$3.95');
insert into car (id, make, model, price) values (45, 'BMW', '3 Series', '$2.67');
insert into car (id, make, model, price) values (46, 'Land Rover', 'Defender 90', '$8.88');
insert into car (id, make, model, price) values (47, 'Lexus', 'SC', '$7.17');
insert into car (id, make, model, price) values (48, 'Pontiac', 'Firefly', '$5.28');
insert into car (id, make, model, price) values (49, 'Chevrolet', 'Silverado', '$2.20');
insert into car (id, make, model, price) values (50, 'BMW', '5 Series', '$8.39');
insert into car (id, make, model, price) values (51, 'Chevrolet', 'Corvette', '$8.60');
insert into car (id, make, model, price) values (52, 'Ford', 'F-Series Super Duty', '$3.08');
insert into car (id, make, model, price) values (53, 'Volvo', 'XC70', '$4.71');
insert into car (id, make, model, price) values (54, 'Isuzu', 'Trooper', '$7.16');
insert into car (id, make, model, price) values (55, 'Dodge', 'Ram 1500', '$8.26');
insert into car (id, make, model, price) values (56, 'Jaguar', 'XK', '$7.77');
insert into car (id, make, model, price) values (57, 'Porsche', 'Cayman', '$4.50');
insert into car (id, make, model, price) values (58, 'Lexus', 'RX', '$6.04');
insert into car (id, make, model, price) values (59, 'Pontiac', 'Bonneville', '$7.21');
insert into car (id, make, model, price) values (60, 'Suzuki', 'Swift', '$6.64');
insert into car (id, make, model, price) values (61, 'Toyota', 'Celica', '$2.13');
insert into car (id, make, model, price) values (62, 'Dodge', 'Avenger', '$2.76');
insert into car (id, make, model, price) values (63, 'Ford', 'F-Series', '$3.29');
insert into car (id, make, model, price) values (64, 'Dodge', 'Grand Caravan', '$1.53');
insert into car (id, make, model, price) values (65, 'Volkswagen', 'R32', '$1.44');
insert into car (id, make, model, price) values (66, 'Mazda', 'RX-8', '$6.71');
insert into car (id, make, model, price) values (67, 'Land Rover', 'Discovery', '$3.91');
insert into car (id, make, model, price) values (68, 'GMC', 'Acadia', '$5.94');
insert into car (id, make, model, price) values (69, 'Lincoln', 'Continental Mark VII', '$5.98');
insert into car (id, make, model, price) values (70, 'Mazda', 'RX-7', '$3.30');
insert into car (id, make, model, price) values (71, 'Mercedes-Benz', 'Sprinter 2500', '$6.41');
insert into car (id, make, model, price) values (72, 'Lotus', 'Elan', '$1.38');
insert into car (id, make, model, price) values (73, 'Buick', 'Skyhawk', '$2.08');
insert into car (id, make, model, price) values (74, 'Scion', 'xD', '$0.67');
insert into car (id, make, model, price) values (75, 'BMW', 'X3', '$8.25');
insert into car (id, make, model, price) values (76, 'Toyota', 'Camry Solara', '$1.83');
insert into car (id, make, model, price) values (77, 'Chrysler', 'Town & Country', '$7.09');
insert into car (id, make, model, price) values (78, 'Volvo', 'S60', '$7.24');
insert into car (id, make, model, price) values (79, 'Jeep', 'Grand Cherokee', '$2.05');
insert into car (id, make, model, price) values (80, 'Buick', 'Enclave', '$2.92');
insert into car (id, make, model, price) values (81, 'Mazda', '323', '$4.37');
insert into car (id, make, model, price) values (82, 'GMC', 'Sierra 3500', '$2.81');
insert into car (id, make, model, price) values (83, 'Jeep', 'Wrangler', '$6.84');
insert into car (id, make, model, price) values (84, 'Subaru', 'Legacy', '$2.68');
insert into car (id, make, model, price) values (85, 'Mercedes-Benz', 'SLR McLaren', '$6.47');
insert into car (id, make, model, price) values (86, 'Hyundai', 'Elantra', '$6.08');
insert into car (id, make, model, price) values (87, 'Jeep', 'Liberty', '$0.33');
insert into car (id, make, model, price) values (88, 'Pontiac', 'Monterey', '$9.86');
insert into car (id, make, model, price) values (89, 'Ford', 'Ranger', '$1.11');
insert into car (id, make, model, price) values (90, 'Ford', 'Club Wagon', '$4.13');
insert into car (id, make, model, price) values (91, 'Mercedes-Benz', 'S-Class', '$1.46');
insert into car (id, make, model, price) values (92, 'Pontiac', 'Grand Prix', '$5.34');
insert into car (id, make, model, price) values (93, 'Mitsubishi', 'Mighty Max', '$9.73');
insert into car (id, make, model, price) values (94, 'Dodge', 'Caravan', '$3.61');
insert into car (id, make, model, price) values (95, 'Hyundai', 'Azera', '$1.78');
insert into car (id, make, model, price) values (96, 'Dodge', 'Ram 3500', '$5.72');
insert into car (id, make, model, price) values (97, 'BMW', 'Z8', '$1.53');
insert into car (id, make, model, price) values (98, 'Mitsubishi', 'Galant', '$7.81');
insert into car (id, make, model, price) values (99, 'Rolls-Royce', 'Phantom', '$2.24');
insert into car (id, make, model, price) values (100, 'Chrysler', '300', '$1.83');
insert into car (id, make, model, price) values (101, 'Plymouth', 'Acclaim', '$1.78');
insert into car (id, make, model, price) values (102, 'Chevrolet', 'Equinox', '$4.72');
insert into car (id, make, model, price) values (103, 'Hyundai', 'Scoupe', '$1.38');
insert into car (id, make, model, price) values (104, 'Audi', 'S4', '$2.88');
insert into car (id, make, model, price) values (105, 'Chevrolet', 'Impala', '$9.13');
insert into car (id, make, model, price) values (106, 'Chevrolet', 'G-Series 1500', '$0.78');
insert into car (id, make, model, price) values (107, 'Jeep', 'Wrangler', '$2.93');
insert into car (id, make, model, price) values (108, 'Volvo', 'S80', '$0.89');
insert into car (id, make, model, price) values (109, 'Pontiac', 'G8', '$5.46');
insert into car (id, make, model, price) values (110, 'Dodge', 'Magnum', '$9.59');
insert into car (id, make, model, price) values (111, 'Maybach', '57', '$2.94');
insert into car (id, make, model, price) values (112, 'Suzuki', 'Samurai', '$7.86');
insert into car (id, make, model, price) values (113, 'Audi', 'Q5', '$9.49');
insert into car (id, make, model, price) values (114, 'GMC', 'Savana 2500', '$8.08');
insert into car (id, make, model, price) values (115, 'Maserati', 'GranSport', '$6.24');
insert into car (id, make, model, price) values (116, 'Chevrolet', 'Corvette', '$8.28');
insert into car (id, make, model, price) values (117, 'Dodge', 'Ram Van 1500', '$7.36');
insert into car (id, make, model, price) values (118, 'Kia', 'Spectra', '$9.87');
insert into car (id, make, model, price) values (119, 'Jaguar', 'XJ', '$8.91');
insert into car (id, make, model, price) values (120, 'Toyota', 'Tacoma', '$5.19');
insert into car (id, make, model, price) values (121, 'GMC', 'Savana 2500', '$7.06');
insert into car (id, make, model, price) values (122, 'Toyota', 'Corolla', '$9.89');
insert into car (id, make, model, price) values (123, 'GMC', 'Suburban 2500', '$6.64');
insert into car (id, make, model, price) values (124, 'Kia', 'Sportage', '$7.74');
insert into car (id, make, model, price) values (125, 'Mitsubishi', 'Eclipse', '$5.61');
insert into car (id, make, model, price) values (126, 'Chevrolet', 'Avalanche 1500', '$5.44');
insert into car (id, make, model, price) values (127, 'Dodge', 'Caravan', '$5.94');
insert into car (id, make, model, price) values (128, 'Toyota', 'Celica', '$6.47');
insert into car (id, make, model, price) values (129, 'Chevrolet', 'Cavalier', '$6.15');
insert into car (id, make, model, price) values (130, 'Ford', 'F-Series Super Duty', '$3.26');
insert into car (id, make, model, price) values (131, 'Mercedes-Benz', 'CL-Class', '$8.57');
insert into car (id, make, model, price) values (132, 'Ford', 'F-Series', '$5.57');
insert into car (id, make, model, price) values (133, 'Lexus', 'LFA', '$4.62');
insert into car (id, make, model, price) values (134, 'Mercedes-Benz', 'R-Class', '$3.21');
insert into car (id, make, model, price) values (135, 'Plymouth', 'Neon', '$9.26');
insert into car (id, make, model, price) values (136, 'Buick', 'Regal', '$0.21');
insert into car (id, make, model, price) values (137, 'Cadillac', 'CTS', '$3.97');
insert into car (id, make, model, price) values (138, 'Austin', 'Mini Cooper S', '$5.75');
insert into car (id, make, model, price) values (139, 'Volvo', 'XC60', '$6.22');
insert into car (id, make, model, price) values (140, 'Infiniti', 'G37', '$9.19');
insert into car (id, make, model, price) values (141, 'Pontiac', 'GTO', '$1.14');
insert into car (id, make, model, price) values (142, 'Buick', 'Enclave', '$3.02');
insert into car (id, make, model, price) values (143, 'Pontiac', 'GTO', '$6.87');
insert into car (id, make, model, price) values (144, 'Plymouth', 'Colt', '$7.85');
insert into car (id, make, model, price) values (145, 'BMW', 'M3', '$2.59');
insert into car (id, make, model, price) values (146, 'Toyota', 'Avalon', '$1.41');
insert into car (id, make, model, price) values (147, 'Chevrolet', 'Cobalt', '$9.83');
insert into car (id, make, model, price) values (148, 'GMC', 'Sonoma', '$2.58');
insert into car (id, make, model, price) values (149, 'Infiniti', 'G', '$4.51');
insert into car (id, make, model, price) values (150, 'Ford', 'F150', '$5.92');
insert into car (id, make, model, price) values (151, 'Aston Martin', 'DB9', '$2.08');
insert into car (id, make, model, price) values (152, 'Toyota', 'Corolla', '$1.13');
insert into car (id, make, model, price) values (153, 'Honda', 'Fit', '$4.71');
insert into car (id, make, model, price) values (154, 'Toyota', 'Avalon', '$3.70');
insert into car (id, make, model, price) values (155, 'Saturn', 'L-Series', '$8.39');
insert into car (id, make, model, price) values (156, 'Pontiac', 'Firebird', '$4.43');
insert into car (id, make, model, price) values (157, 'Maybach', '57', '$3.91');
insert into car (id, make, model, price) values (158, 'Acura', 'MDX', '$4.73');
insert into car (id, make, model, price) values (159, 'Mercedes-Benz', 'W123', '$3.29');
insert into car (id, make, model, price) values (160, 'Dodge', 'Ram 1500', '$8.18');
insert into car (id, make, model, price) values (161, 'Hyundai', 'Sonata', '$6.08');
insert into car (id, make, model, price) values (162, 'Mazda', 'B-Series', '$5.33');
insert into car (id, make, model, price) values (163, 'Audi', 'S5', '$7.01');
insert into car (id, make, model, price) values (164, 'Audi', 'RS4', '$4.31');
insert into car (id, make, model, price) values (165, 'Chevrolet', 'Astro', '$7.72');
insert into car (id, make, model, price) values (166, 'Ford', 'E-Series', '$8.26');
insert into car (id, make, model, price) values (167, 'Bentley', 'Mulsanne', '$6.28');
insert into car (id, make, model, price) values (168, 'Honda', 'Civic', '$3.76');
insert into car (id, make, model, price) values (169, 'Isuzu', 'Ascender', '$0.02');
insert into car (id, make, model, price) values (170, 'GMC', 'Terrain', '$3.92');
insert into car (id, make, model, price) values (171, 'Chevrolet', 'Sportvan G20', '$1.80');
insert into car (id, make, model, price) values (172, 'Lexus', 'CT', '$2.06');
insert into car (id, make, model, price) values (173, 'Chevrolet', 'Cobalt', '$1.21');
insert into car (id, make, model, price) values (174, 'Lotus', 'Exige', '$3.16');
insert into car (id, make, model, price) values (175, 'Mitsubishi', 'Lancer Evolution', '$9.86');
insert into car (id, make, model, price) values (176, 'Hyundai', 'Veracruz', '$2.90');
insert into car (id, make, model, price) values (177, 'Buick', 'Century', '$1.27');
insert into car (id, make, model, price) values (178, 'Volvo', 'XC90', '$4.11');
insert into car (id, make, model, price) values (179, 'Infiniti', 'QX', '$1.27');
insert into car (id, make, model, price) values (180, 'Ferrari', '612 Scaglietti', '$4.97');
insert into car (id, make, model, price) values (181, 'Cadillac', 'Fleetwood', '$9.68');
insert into car (id, make, model, price) values (182, 'Toyota', 'Cressida', '$0.94');
insert into car (id, make, model, price) values (183, 'Lexus', 'ES', '$2.70');
insert into car (id, make, model, price) values (184, 'Nissan', 'Xterra', '$0.81');
insert into car (id, make, model, price) values (185, 'Audi', 'A8', '$1.20');
insert into car (id, make, model, price) values (186, 'Porsche', '944', '$6.75');
insert into car (id, make, model, price) values (187, 'Ford', 'Freestar', '$8.06');
insert into car (id, make, model, price) values (188, 'Chevrolet', 'G-Series G10', '$5.97');
insert into car (id, make, model, price) values (189, 'Suzuki', 'Swift', '$4.85');
insert into car (id, make, model, price) values (190, 'Volvo', 'S60', '$9.93');
insert into car (id, make, model, price) values (191, 'Buick', 'LeSabre', '$6.78');
insert into car (id, make, model, price) values (192, 'Buick', 'Regal', '$2.85');
insert into car (id, make, model, price) values (193, 'Volkswagen', 'Jetta', '$3.95');
insert into car (id, make, model, price) values (194, 'Audi', 'V8', '$6.51');
insert into car (id, make, model, price) values (195, 'Subaru', 'Legacy', '$4.05');
insert into car (id, make, model, price) values (196, 'Citroën', 'CX', '$6.64');
insert into car (id, make, model, price) values (197, 'Ford', 'Taurus', '$2.72');
insert into car (id, make, model, price) values (198, 'Chrysler', 'Crossfire', '$5.44');
insert into car (id, make, model, price) values (199, 'Mercedes-Benz', 'SLK-Class', '$2.64');
insert into car (id, make, model, price) values (200, 'Kia', 'Sportage', '$5.43');
insert into car (id, make, model, price) values (201, 'Maserati', 'Spyder', '$0.58');
insert into car (id, make, model, price) values (202, 'Chevrolet', 'Corvette', '$4.53');
insert into car (id, make, model, price) values (203, 'Volkswagen', 'riolet', '$5.23');
insert into car (id, make, model, price) values (204, 'Subaru', 'Brat', '$3.24');
insert into car (id, make, model, price) values (205, 'Lamborghini', 'Diablo', '$1.15');
insert into car (id, make, model, price) values (206, 'BMW', 'M3', '$3.54');
insert into car (id, make, model, price) values (207, 'Subaru', 'Forester', '$1.49');
insert into car (id, make, model, price) values (208, 'Chevrolet', '3500', '$9.72');
insert into car (id, make, model, price) values (209, 'Mitsubishi', 'Mighty Max', '$5.18');
insert into car (id, make, model, price) values (210, 'Suzuki', 'Grand Vitara', '$9.21');
insert into car (id, make, model, price) values (211, 'Mazda', 'B-Series', '$9.00');
insert into car (id, make, model, price) values (212, 'Chevrolet', 'Tracker', '$1.78');
insert into car (id, make, model, price) values (213, 'Chevrolet', 'Silverado 3500', '$4.60');
insert into car (id, make, model, price) values (214, 'Pontiac', 'GTO', '$6.47');
insert into car (id, make, model, price) values (215, 'Honda', 'Odyssey', '$2.84');
insert into car (id, make, model, price) values (216, 'Dodge', 'Intrepid', '$1.17');
insert into car (id, make, model, price) values (217, 'Chrysler', 'Town & Country', '$6.12');
insert into car (id, make, model, price) values (218, 'Ford', 'Mustang', '$9.96');
insert into car (id, make, model, price) values (219, 'Buick', 'Regal', '$5.79');
insert into car (id, make, model, price) values (220, 'Mitsubishi', 'Galant', '$6.83');
insert into car (id, make, model, price) values (221, 'Mitsubishi', 'Galant', '$5.10');
insert into car (id, make, model, price) values (222, 'Buick', 'Skyhawk', '$8.85');
insert into car (id, make, model, price) values (223, 'Kia', 'Rio', '$2.24');
insert into car (id, make, model, price) values (224, 'Saturn', 'VUE', '$4.42');
insert into car (id, make, model, price) values (225, 'Maybach', '57', '$1.26');
insert into car (id, make, model, price) values (226, 'Nissan', 'Pathfinder', '$1.39');
insert into car (id, make, model, price) values (227, 'Saab', '9-3', '$0.25');
insert into car (id, make, model, price) values (228, 'Chevrolet', 'Corvette', '$4.53');
insert into car (id, make, model, price) values (229, 'Ford', 'F-Series', '$6.94');
insert into car (id, make, model, price) values (230, 'Jaguar', 'XJ', '$8.40');
insert into car (id, make, model, price) values (231, 'Jeep', 'Comanche', '$8.94');
insert into car (id, make, model, price) values (232, 'Maybach', '62', '$2.60');
insert into car (id, make, model, price) values (233, 'Isuzu', 'Rodeo', '$5.79');
insert into car (id, make, model, price) values (234, 'Chevrolet', 'TrailBlazer', '$3.43');
insert into car (id, make, model, price) values (235, 'Suzuki', 'Vitara', '$0.69');
insert into car (id, make, model, price) values (236, 'Dodge', 'Durango', '$1.92');
insert into car (id, make, model, price) values (237, 'Nissan', 'GT-R', '$6.11');
insert into car (id, make, model, price) values (238, 'Mitsubishi', 'Montero', '$7.89');
insert into car (id, make, model, price) values (239, 'Oldsmobile', '98', '$1.43');
insert into car (id, make, model, price) values (240, 'Ford', 'Tempo', '$3.36');
insert into car (id, make, model, price) values (241, 'Dodge', 'Dakota Club', '$1.13');
insert into car (id, make, model, price) values (242, 'Dodge', 'Dakota Club', '$3.35');
insert into car (id, make, model, price) values (243, 'Toyota', 'Camry Hybrid', '$2.85');
insert into car (id, make, model, price) values (244, 'Volvo', 'XC90', '$6.57');
insert into car (id, make, model, price) values (245, 'Dodge', 'Ram 1500', '$3.56');
insert into car (id, make, model, price) values (246, 'Dodge', 'Ram 1500', '$3.72');
insert into car (id, make, model, price) values (247, 'Ford', 'Focus ST', '$3.09');
insert into car (id, make, model, price) values (248, 'Ford', 'E-Series', '$0.55');
insert into car (id, make, model, price) values (249, 'Ford', 'E-Series', '$7.00');
insert into car (id, make, model, price) values (250, 'BMW', 'X5', '$7.32');
insert into car (id, make, model, price) values (251, 'BMW', 'X6', '$1.32');
insert into car (id, make, model, price) values (252, 'Chevrolet', 'Venture', '$3.70');
insert into car (id, make, model, price) values (253, 'Pontiac', '6000', '$8.92');
insert into car (id, make, model, price) values (254, 'Infiniti', 'I', '$2.88');
insert into car (id, make, model, price) values (255, 'Toyota', 'Solara', '$3.50');
insert into car (id, make, model, price) values (256, 'Lexus', 'GS', '$2.84');
insert into car (id, make, model, price) values (257, 'Ford', 'E-Series', '$8.19');
insert into car (id, make, model, price) values (258, 'Nissan', 'Maxima', '$6.74');
insert into car (id, make, model, price) values (259, 'Dodge', 'Grand Caravan', '$2.32');
insert into car (id, make, model, price) values (260, 'GMC', 'Rally Wagon 2500', '$8.83');
insert into car (id, make, model, price) values (261, 'Pontiac', 'Firebird Trans Am', '$2.16');
insert into car (id, make, model, price) values (262, 'Audi', 'V8', '$9.35');
insert into car (id, make, model, price) values (263, 'BMW', 'M5', '$6.31');
insert into car (id, make, model, price) values (264, 'Toyota', 'Supra', '$2.72');
insert into car (id, make, model, price) values (265, 'Kia', 'Sportage', '$8.28');
insert into car (id, make, model, price) values (266, 'Cadillac', 'Eldorado', '$0.65');
insert into car (id, make, model, price) values (267, 'Mazda', 'Miata MX-5', '$0.91');
insert into car (id, make, model, price) values (268, 'Volvo', '740', '$6.29');
insert into car (id, make, model, price) values (269, 'Land Rover', 'Discovery Series II', '$7.26');
insert into car (id, make, model, price) values (270, 'Alfa Romeo', 'Spider', '$6.81');
insert into car (id, make, model, price) values (271, 'Mazda', 'B2500', '$0.34');
insert into car (id, make, model, price) values (272, 'Cadillac', 'Escalade', '$5.77');
insert into car (id, make, model, price) values (273, 'Lincoln', 'Blackwood', '$9.98');
insert into car (id, make, model, price) values (274, 'Ford', 'Contour', '$7.68');
insert into car (id, make, model, price) values (275, 'Pontiac', 'Aztek', '$7.37');
insert into car (id, make, model, price) values (276, 'Nissan', 'Altima', '$2.61');
insert into car (id, make, model, price) values (277, 'Toyota', 'Previa', '$4.08');
insert into car (id, make, model, price) values (278, 'Jeep', 'Wrangler', '$1.81');
insert into car (id, make, model, price) values (279, 'Ford', 'Taurus', '$3.34');
insert into car (id, make, model, price) values (280, 'Jaguar', 'XJ Series', '$8.11');
insert into car (id, make, model, price) values (281, 'Nissan', 'Maxima', '$3.45');
insert into car (id, make, model, price) values (282, 'Honda', 'Prelude', '$6.39');
insert into car (id, make, model, price) values (283, 'Chevrolet', 'Equinox', '$9.33');
insert into car (id, make, model, price) values (284, 'GMC', 'Sierra 3500', '$7.67');
insert into car (id, make, model, price) values (285, 'Chevrolet', 'Avalanche 2500', '$4.70');
insert into car (id, make, model, price) values (286, 'Mazda', 'Tribute', '$4.54');
insert into car (id, make, model, price) values (287, 'Hyundai', 'Santa Fe', '$0.20');
insert into car (id, make, model, price) values (288, 'Ford', 'Explorer', '$5.68');
insert into car (id, make, model, price) values (289, 'Pontiac', 'Firefly', '$2.19');
insert into car (id, make, model, price) values (290, 'Dodge', 'Caravan', '$1.38');
insert into car (id, make, model, price) values (291, 'Isuzu', 'Trooper', '$3.58');
insert into car (id, make, model, price) values (292, 'Pontiac', 'Sunbird', '$4.32');
insert into car (id, make, model, price) values (293, 'Suzuki', 'Aerio', '$2.86');
insert into car (id, make, model, price) values (294, 'Ford', 'Freestar', '$7.48');
insert into car (id, make, model, price) values (295, 'Dodge', 'D150 Club', '$8.74');
insert into car (id, make, model, price) values (296, 'Mercedes-Benz', 'E-Class', '$5.01');
insert into car (id, make, model, price) values (297, 'BMW', 'X3', '$1.16');
insert into car (id, make, model, price) values (298, 'Saturn', 'VUE', '$7.90');
insert into car (id, make, model, price) values (299, 'Mercury', 'Mountaineer', '$3.46');
insert into car (id, make, model, price) values (300, 'Land Rover', 'Discovery', '$0.50');
insert into car (id, make, model, price) values (301, 'Audi', 'Coupe Quattro', '$8.41');
insert into car (id, make, model, price) values (302, 'Hummer', 'H3', '$8.22');
insert into car (id, make, model, price) values (303, 'Volkswagen', 'New Beetle', '$8.26');
insert into car (id, make, model, price) values (304, 'Mazda', 'Familia', '$8.16');
insert into car (id, make, model, price) values (305, 'Mitsubishi', 'Diamante', '$5.78');
insert into car (id, make, model, price) values (306, 'Plymouth', 'Neon', '$1.32');
insert into car (id, make, model, price) values (307, 'Oldsmobile', 'Bravada', '$4.17');
insert into car (id, make, model, price) values (308, 'Mazda', 'Navajo', '$1.60');
insert into car (id, make, model, price) values (309, 'Dodge', 'Caravan', '$1.20');
insert into car (id, make, model, price) values (310, 'Saturn', 'Relay', '$0.57');
insert into car (id, make, model, price) values (311, 'Lamborghini', 'Gallardo', '$2.57');
insert into car (id, make, model, price) values (312, 'Cadillac', 'Eldorado', '$5.55');
insert into car (id, make, model, price) values (313, 'GMC', '1500', '$9.94');
insert into car (id, make, model, price) values (314, 'Mitsubishi', 'Challenger', '$8.62');
insert into car (id, make, model, price) values (315, 'Saab', '9-5', '$5.70');
insert into car (id, make, model, price) values (316, 'Mercury', 'Villager', '$2.66');
insert into car (id, make, model, price) values (317, 'Honda', 'Prelude', '$2.11');
insert into car (id, make, model, price) values (318, 'Honda', 'CR-V', '$5.10');
insert into car (id, make, model, price) values (319, 'Mercury', 'Sable', '$3.39');
insert into car (id, make, model, price) values (320, 'Ford', 'F-Series', '$7.00');
insert into car (id, make, model, price) values (321, 'Mercury', 'Topaz', '$3.23');
insert into car (id, make, model, price) values (322, 'Lincoln', 'Navigator', '$1.92');
insert into car (id, make, model, price) values (323, 'Ford', 'F450', '$4.38');
insert into car (id, make, model, price) values (324, 'Land Rover', 'Freelander', '$7.09');
insert into car (id, make, model, price) values (325, 'Mercury', 'Sable', '$8.74');
insert into car (id, make, model, price) values (326, 'Kia', 'Rio', '$2.23');
insert into car (id, make, model, price) values (327, 'Buick', 'Park Avenue', '$1.45');
insert into car (id, make, model, price) values (328, 'Dodge', 'Ram', '$9.09');
insert into car (id, make, model, price) values (329, 'Kia', 'Sedona', '$1.51');
insert into car (id, make, model, price) values (330, 'Chevrolet', 'Suburban 1500', '$8.18');
insert into car (id, make, model, price) values (331, 'Toyota', 'Highlander', '$5.10');
insert into car (id, make, model, price) values (332, 'Volkswagen', 'Rabbit', '$6.30');
insert into car (id, make, model, price) values (333, 'Chevrolet', 'Lumina', '$5.90');
insert into car (id, make, model, price) values (334, 'Bentley', 'Continental Super', '$2.21');
insert into car (id, make, model, price) values (335, 'Lexus', 'LS', '$7.88');
insert into car (id, make, model, price) values (336, 'Nissan', 'Pathfinder', '$7.77');
insert into car (id, make, model, price) values (337, 'Volkswagen', 'Cabriolet', '$2.33');
insert into car (id, make, model, price) values (338, 'Dodge', 'Grand Caravan', '$2.63');
insert into car (id, make, model, price) values (339, 'Saab', '9-7X', '$1.84');
insert into car (id, make, model, price) values (340, 'Dodge', 'Ram Van 2500', '$3.58');
insert into car (id, make, model, price) values (341, 'Ford', 'F350', '$9.42');
insert into car (id, make, model, price) values (342, 'Ford', 'Taurus', '$5.99');
insert into car (id, make, model, price) values (343, 'Acura', 'TSX', '$2.78');
insert into car (id, make, model, price) values (344, 'Dodge', 'Caliber', '$1.43');
insert into car (id, make, model, price) values (345, 'Mitsubishi', 'Challenger', '$4.46');
insert into car (id, make, model, price) values (346, 'GMC', 'Sonoma Club Coupe', '$7.15');
insert into car (id, make, model, price) values (347, 'Jaguar', 'XK Series', '$6.36');
insert into car (id, make, model, price) values (348, 'Chevrolet', 'Suburban', '$2.87');
insert into car (id, make, model, price) values (349, 'Mercedes-Benz', 'CLS-Class', '$2.73');
insert into car (id, make, model, price) values (350, 'Acura', 'Integra', '$4.75');
insert into car (id, make, model, price) values (351, 'Ford', 'Thunderbird', '$8.29');
insert into car (id, make, model, price) values (352, 'BMW', 'X5', '$7.13');
insert into car (id, make, model, price) values (353, 'Mercury', 'Mystique', '$3.24');
insert into car (id, make, model, price) values (354, 'Ford', 'Focus', '$7.46');
insert into car (id, make, model, price) values (355, 'Volvo', '940', '$8.81');
insert into car (id, make, model, price) values (356, 'Mercury', 'Cougar', '$6.62');
insert into car (id, make, model, price) values (357, 'Nissan', 'Murano', '$9.31');
insert into car (id, make, model, price) values (358, 'Mercedes-Benz', 'M-Class', '$8.29');
insert into car (id, make, model, price) values (359, 'Volvo', '940', '$5.14');
insert into car (id, make, model, price) values (360, 'Dodge', 'Ram 2500', '$5.74');
insert into car (id, make, model, price) values (361, 'GMC', 'Suburban 1500', '$9.98');
insert into car (id, make, model, price) values (362, 'Chevrolet', 'Silverado 2500', '$4.95');
insert into car (id, make, model, price) values (363, 'Chevrolet', 'Impala', '$1.37');
insert into car (id, make, model, price) values (364, 'Mercedes-Benz', 'M-Class', '$4.26');
insert into car (id, make, model, price) values (365, 'Oldsmobile', 'Regency', '$9.35');
insert into car (id, make, model, price) values (366, 'Chevrolet', 'Corsica', '$6.77');
insert into car (id, make, model, price) values (367, 'Volkswagen', 'Passat', '$3.15');
insert into car (id, make, model, price) values (368, 'Oldsmobile', '88', '$8.11');
insert into car (id, make, model, price) values (369, 'Buick', 'Skyhawk', '$6.78');
insert into car (id, make, model, price) values (370, 'Mercedes-Benz', 'SL-Class', '$6.19');
insert into car (id, make, model, price) values (371, 'Ford', 'Fusion', '$2.29');
insert into car (id, make, model, price) values (372, 'Chevrolet', 'Astro', '$2.47');
insert into car (id, make, model, price) values (373, 'Honda', 'Accord', '$2.62');
insert into car (id, make, model, price) values (374, 'Pontiac', 'Tempest', '$0.69');
insert into car (id, make, model, price) values (375, 'Mercedes-Benz', '300CE', '$3.13');
insert into car (id, make, model, price) values (376, 'GMC', '3500 Club Coupe', '$7.40');
insert into car (id, make, model, price) values (377, 'Saturn', 'S-Series', '$5.73');
insert into car (id, make, model, price) values (378, 'Oldsmobile', 'LSS', '$2.71');
insert into car (id, make, model, price) values (379, 'Nissan', 'Sentra', '$3.37');
insert into car (id, make, model, price) values (380, 'Ford', 'F250', '$7.17');
insert into car (id, make, model, price) values (381, 'GMC', 'Savana', '$5.87');
insert into car (id, make, model, price) values (382, 'Dodge', 'Avenger', '$9.51');
insert into car (id, make, model, price) values (383, 'Mazda', 'B-Series Plus', '$5.98');
insert into car (id, make, model, price) values (384, 'GMC', 'Savana 3500', '$5.97');
insert into car (id, make, model, price) values (385, 'Audi', 'Allroad', '$3.30');
insert into car (id, make, model, price) values (386, 'Toyota', 'FJ Cruiser', '$2.09');
insert into car (id, make, model, price) values (387, 'Audi', 'S6', '$0.48');
insert into car (id, make, model, price) values (388, 'Infiniti', 'IPL G', '$4.17');
insert into car (id, make, model, price) values (389, 'Audi', 'A5', '$0.84');
insert into car (id, make, model, price) values (390, 'Ford', 'Mustang', '$6.13');
insert into car (id, make, model, price) values (391, 'Lexus', 'GX', '$9.58');
insert into car (id, make, model, price) values (392, 'Pontiac', 'Sunfire', '$3.72');
insert into car (id, make, model, price) values (393, 'Volkswagen', 'rio', '$0.58');
insert into car (id, make, model, price) values (394, 'Audi', 'S6', '$0.72');
insert into car (id, make, model, price) values (395, 'Chrysler', 'Concorde', '$9.65');
insert into car (id, make, model, price) values (396, 'Suzuki', 'Grand Vitara', '$6.66');
insert into car (id, make, model, price) values (397, 'Subaru', 'Legacy', '$9.38');
insert into car (id, make, model, price) values (398, 'BMW', '5 Series', '$8.84');
insert into car (id, make, model, price) values (399, 'Cadillac', 'Seville', '$9.40');
insert into car (id, make, model, price) values (400, 'Dodge', 'Stratus', '$4.96');
insert into car (id, make, model, price) values (401, 'Volvo', 'S60', '$8.08');
insert into car (id, make, model, price) values (402, 'BMW', '530', '$8.90');
insert into car (id, make, model, price) values (403, 'Mitsubishi', 'Chariot', '$1.08');
insert into car (id, make, model, price) values (404, 'Pontiac', 'Sunbird', '$7.14');
insert into car (id, make, model, price) values (405, 'Honda', 'S2000', '$5.43');
insert into car (id, make, model, price) values (406, 'Cadillac', 'CTS-V', '$0.91');
insert into car (id, make, model, price) values (407, 'GMC', 'Yukon', '$6.88');
insert into car (id, make, model, price) values (408, 'Chrysler', '300', '$2.65');
insert into car (id, make, model, price) values (409, 'Mercedes-Benz', 'CL-Class', '$2.62');
insert into car (id, make, model, price) values (410, 'Mercedes-Benz', 'S-Class', '$6.01');
insert into car (id, make, model, price) values (411, 'Mazda', 'MPV', '$1.86');
insert into car (id, make, model, price) values (412, 'Pontiac', 'Grand Prix', '$9.79');
insert into car (id, make, model, price) values (413, 'Honda', 'Accord', '$1.92');
insert into car (id, make, model, price) values (414, 'Ferrari', '612 Scaglietti', '$3.02');
insert into car (id, make, model, price) values (415, 'Geo', 'Tracker', '$9.92');
insert into car (id, make, model, price) values (416, 'Maserati', '430', '$7.36');
insert into car (id, make, model, price) values (417, 'Infiniti', 'FX', '$8.24');
insert into car (id, make, model, price) values (418, 'Chevrolet', 'Beretta', '$3.33');
insert into car (id, make, model, price) values (419, 'Mercedes-Benz', 'E-Class', '$7.81');
insert into car (id, make, model, price) values (420, 'Kia', 'Sedona', '$3.76');
insert into car (id, make, model, price) values (421, 'Nissan', 'Maxima', '$3.18');
insert into car (id, make, model, price) values (422, 'Bentley', 'Continental GT', '$1.70');
insert into car (id, make, model, price) values (423, 'Toyota', 'Prius', '$2.04');
insert into car (id, make, model, price) values (424, 'Toyota', 'Tacoma', '$9.19');
insert into car (id, make, model, price) values (425, 'Subaru', 'Legacy', '$4.67');
insert into car (id, make, model, price) values (426, 'Bentley', 'Arnage', '$7.16');
insert into car (id, make, model, price) values (427, 'Isuzu', 'Trooper', '$2.74');
insert into car (id, make, model, price) values (428, 'Jaguar', 'S-Type', '$6.02');
insert into car (id, make, model, price) values (429, 'Volkswagen', 'Vanagon', '$2.29');
insert into car (id, make, model, price) values (430, 'Subaru', 'Loyale', '$7.83');
insert into car (id, make, model, price) values (431, 'GMC', '1500 Club Coupe', '$9.22');
insert into car (id, make, model, price) values (432, 'Saturn', 'Sky', '$9.42');
insert into car (id, make, model, price) values (433, 'Jeep', 'Patriot', '$3.83');
insert into car (id, make, model, price) values (434, 'Pontiac', 'Firebird Trans Am', '$1.40');
insert into car (id, make, model, price) values (435, 'Jeep', 'Wrangler', '$2.82');
insert into car (id, make, model, price) values (436, 'Toyota', 'Land Cruiser', '$3.50');
insert into car (id, make, model, price) values (437, 'Oldsmobile', '88', '$3.08');
insert into car (id, make, model, price) values (438, 'Ford', 'E150', '$1.11');
insert into car (id, make, model, price) values (439, 'Volkswagen', 'Cabriolet', '$0.93');
insert into car (id, make, model, price) values (440, 'Subaru', 'Brat', '$8.90');
insert into car (id, make, model, price) values (441, 'Oldsmobile', 'Bravada', '$4.84');
insert into car (id, make, model, price) values (442, 'Ford', 'Expedition', '$7.82');
insert into car (id, make, model, price) values (443, 'Daewoo', 'Nubira', '$4.84');
insert into car (id, make, model, price) values (444, 'Land Rover', 'Freelander', '$8.14');
insert into car (id, make, model, price) values (445, 'Land Rover', 'Discovery', '$7.08');
insert into car (id, make, model, price) values (446, 'Suzuki', 'Equator', '$0.25');
insert into car (id, make, model, price) values (447, 'Dodge', 'Caravan', '$3.83');
insert into car (id, make, model, price) values (448, 'Lincoln', 'Continental Mark VII', '$5.28');
insert into car (id, make, model, price) values (449, 'Hyundai', 'Accent', '$0.08');
insert into car (id, make, model, price) values (450, 'Dodge', 'Dakota Club', '$7.64');
insert into car (id, make, model, price) values (451, 'Ford', 'Taurus', '$6.15');
insert into car (id, make, model, price) values (452, 'Mercury', 'Grand Marquis', '$2.40');
insert into car (id, make, model, price) values (453, 'Honda', 'Passport', '$3.76');
insert into car (id, make, model, price) values (454, 'Dodge', 'Grand Caravan', '$1.51');
insert into car (id, make, model, price) values (455, 'Chevrolet', 'Malibu', '$8.67');
insert into car (id, make, model, price) values (456, 'Bentley', 'Azure', '$0.84');
insert into car (id, make, model, price) values (457, 'Volvo', 'V90', '$1.59');
insert into car (id, make, model, price) values (458, 'Mercury', 'Grand Marquis', '$7.05');
insert into car (id, make, model, price) values (459, 'Mitsubishi', 'Eclipse', '$6.86');
insert into car (id, make, model, price) values (460, 'Porsche', '944', '$8.73');
insert into car (id, make, model, price) values (461, 'Mercedes-Benz', '300E', '$2.62');
insert into car (id, make, model, price) values (462, 'Nissan', '370Z', '$7.75');
insert into car (id, make, model, price) values (463, 'Mercury', 'Grand Marquis', '$7.18');
insert into car (id, make, model, price) values (464, 'Mazda', 'Mazda5', '$7.95');
insert into car (id, make, model, price) values (465, 'Mercury', 'Grand Marquis', '$5.82');
insert into car (id, make, model, price) values (466, 'Chevrolet', 'Suburban 1500', '$8.57');
insert into car (id, make, model, price) values (467, 'Merkur', 'XR4Ti', '$9.04');
insert into car (id, make, model, price) values (468, 'Ford', 'Taurus', '$6.70');
insert into car (id, make, model, price) values (469, 'Toyota', 'Camry', '$7.14');
insert into car (id, make, model, price) values (470, 'Acura', 'NSX', '$7.39');
insert into car (id, make, model, price) values (471, 'GMC', 'Vandura G2500', '$4.34');
insert into car (id, make, model, price) values (472, 'Dodge', 'Ram Van 3500', '$7.00');
insert into car (id, make, model, price) values (473, 'MINI', 'Clubman', '$5.16');
insert into car (id, make, model, price) values (474, 'Kia', 'Sedona', '$5.68');
insert into car (id, make, model, price) values (475, 'Chevrolet', 'Caprice Classic', '$9.23');
insert into car (id, make, model, price) values (476, 'Bentley', 'Brooklands', '$5.49');
insert into car (id, make, model, price) values (477, 'Pontiac', 'Firefly', '$7.56');
insert into car (id, make, model, price) values (478, 'Volkswagen', 'Routan', '$5.90');
insert into car (id, make, model, price) values (479, 'Kia', 'Sportage', '$2.22');
insert into car (id, make, model, price) values (480, 'Chevrolet', 'Sportvan G30', '$6.55');
insert into car (id, make, model, price) values (481, 'Audi', 'A4', '$7.38');
insert into car (id, make, model, price) values (482, 'Hyundai', 'Azera', '$8.04');
insert into car (id, make, model, price) values (483, 'Audi', 'TT', '$6.04');
insert into car (id, make, model, price) values (484, 'Infiniti', 'FX', '$1.45');
insert into car (id, make, model, price) values (485, 'Ford', 'GT500', '$6.97');
insert into car (id, make, model, price) values (486, 'Scion', 'xD', '$1.73');
insert into car (id, make, model, price) values (487, 'GMC', 'Yukon', '$6.98');
insert into car (id, make, model, price) values (488, 'Morgan', 'Aero 8', '$3.83');
insert into car (id, make, model, price) values (489, 'Chevrolet', 'Suburban 2500', '$1.03');
insert into car (id, make, model, price) values (490, 'BMW', '745', '$5.13');
insert into car (id, make, model, price) values (491, 'Mazda', 'Mazdaspeed6', '$4.75');
insert into car (id, make, model, price) values (492, 'Volkswagen', 'Jetta', '$2.21');
insert into car (id, make, model, price) values (493, 'Dodge', 'Dakota', '$3.68');
insert into car (id, make, model, price) values (494, 'Mitsubishi', 'Eclipse', '$5.77');
insert into car (id, make, model, price) values (495, 'Mercury', 'Sable', '$4.39');
insert into car (id, make, model, price) values (496, 'GMC', 'Sierra 2500', '$3.85');
insert into car (id, make, model, price) values (497, 'Chevrolet', 'Astro', '$8.66');
insert into car (id, make, model, price) values (498, 'Porsche', 'Boxster', '$1.01');
insert into car (id, make, model, price) values (499, 'Suzuki', 'Swift', '$3.46');
insert into car (id, make, model, price) values (500, 'Volvo', 'S70', '$5.51');
insert into car (id, make, model, price) values (501, 'Mitsubishi', 'Galant', '$5.59');
insert into car (id, make, model, price) values (502, 'Suzuki', 'XL-7', '$2.07');
insert into car (id, make, model, price) values (503, 'Suzuki', 'XL-7', '$1.14');
insert into car (id, make, model, price) values (504, 'Kia', 'Sportage', '$5.63');
insert into car (id, make, model, price) values (505, 'Oldsmobile', 'Silhouette', '$6.81');
insert into car (id, make, model, price) values (506, 'Audi', 'A8', '$7.50');
insert into car (id, make, model, price) values (507, 'Cadillac', 'Allante', '$5.80');
insert into car (id, make, model, price) values (508, 'GMC', '1500', '$0.10');
insert into car (id, make, model, price) values (509, 'Lexus', 'GS', '$8.86');
insert into car (id, make, model, price) values (510, 'BMW', '325', '$8.94');
insert into car (id, make, model, price) values (511, 'Mazda', 'Miata MX-5', '$7.00');
insert into car (id, make, model, price) values (512, 'Lincoln', 'Town Car', '$5.80');
insert into car (id, make, model, price) values (513, 'Audi', 'TT', '$8.28');
insert into car (id, make, model, price) values (514, 'Ford', 'Thunderbird', '$0.78');
insert into car (id, make, model, price) values (515, 'Mitsubishi', 'GTO', '$1.17');
insert into car (id, make, model, price) values (516, 'Ford', 'LTD Crown Victoria', '$0.87');
insert into car (id, make, model, price) values (517, 'Subaru', 'Forester', '$6.18');
insert into car (id, make, model, price) values (518, 'Mercury', 'Capri', '$0.76');
insert into car (id, make, model, price) values (519, 'Acura', 'NSX', '$5.58');
insert into car (id, make, model, price) values (520, 'BMW', 'M5', '$9.18');
insert into car (id, make, model, price) values (521, 'Volvo', '960', '$5.01');
insert into car (id, make, model, price) values (522, 'Dodge', 'Ram Van 2500', '$6.42');
insert into car (id, make, model, price) values (523, 'Volkswagen', 'Rabbit', '$7.14');
insert into car (id, make, model, price) values (524, 'Mercedes-Benz', 'E-Class', '$1.31');
insert into car (id, make, model, price) values (525, 'Honda', 'Accord', '$2.55');
insert into car (id, make, model, price) values (526, 'Land Rover', 'Range Rover', '$9.43');
insert into car (id, make, model, price) values (527, 'Dodge', 'Magnum', '$1.98');
insert into car (id, make, model, price) values (528, 'Mazda', 'Mazda3', '$8.72');
insert into car (id, make, model, price) values (529, 'Mazda', 'Miata MX-5', '$6.91');
insert into car (id, make, model, price) values (530, 'Toyota', 'Celica', '$4.08');
insert into car (id, make, model, price) values (531, 'Cadillac', 'DeVille', '$7.98');
insert into car (id, make, model, price) values (532, 'Audi', 'Coupe Quattro', '$5.78');
insert into car (id, make, model, price) values (533, 'Chevrolet', 'Silverado 1500', '$3.35');
insert into car (id, make, model, price) values (534, 'Chevrolet', 'Tracker', '$8.16');
insert into car (id, make, model, price) values (535, 'Mercedes-Benz', 'C-Class', '$2.76');
insert into car (id, make, model, price) values (536, 'Ford', 'Mustang', '$9.27');
insert into car (id, make, model, price) values (537, 'GMC', 'Terrain', '$2.07');
insert into car (id, make, model, price) values (538, 'Subaru', 'Forester', '$8.60');
insert into car (id, make, model, price) values (539, 'Volvo', 'V70', '$5.38');
insert into car (id, make, model, price) values (540, 'Mitsubishi', 'Pajero', '$2.96');
insert into car (id, make, model, price) values (541, 'Ford', 'Edge', '$7.11');
insert into car (id, make, model, price) values (542, 'Lincoln', 'Navigator', '$0.97');
insert into car (id, make, model, price) values (543, 'Mercury', 'Sable', '$0.75');
insert into car (id, make, model, price) values (544, 'Mitsubishi', 'Montero Sport', '$5.66');
insert into car (id, make, model, price) values (545, 'Fairthorpe', 'Rockette', '$9.89');
insert into car (id, make, model, price) values (546, 'Pontiac', 'Solstice', '$3.81');
insert into car (id, make, model, price) values (547, 'Acura', 'CL', '$8.82');
insert into car (id, make, model, price) values (548, 'Land Rover', 'Range Rover Sport', '$4.40');
insert into car (id, make, model, price) values (549, 'Dodge', 'Viper', '$9.89');
insert into car (id, make, model, price) values (550, 'BMW', 'Z3', '$6.54');
insert into car (id, make, model, price) values (551, 'Volkswagen', 'Golf', '$5.05');
insert into car (id, make, model, price) values (552, 'Porsche', 'Boxster', '$1.02');
insert into car (id, make, model, price) values (553, 'Volkswagen', 'New Beetle', '$7.86');
insert into car (id, make, model, price) values (554, 'Jeep', 'Wrangler', '$1.43');
insert into car (id, make, model, price) values (555, 'Pontiac', 'Bonneville', '$5.90');
insert into car (id, make, model, price) values (556, 'Eagle', 'Vision', '$7.73');
insert into car (id, make, model, price) values (557, 'Buick', 'LeSabre', '$7.71');
insert into car (id, make, model, price) values (558, 'Volkswagen', 'Passat', '$4.96');
insert into car (id, make, model, price) values (559, 'Peugeot', '207', '$9.52');
insert into car (id, make, model, price) values (560, 'GMC', 'Yukon', '$0.60');
insert into car (id, make, model, price) values (561, 'Toyota', 'Tercel', '$1.00');
insert into car (id, make, model, price) values (562, 'Suzuki', 'Esteem', '$3.04');
insert into car (id, make, model, price) values (563, 'Mercedes-Benz', 'S-Class', '$3.14');
insert into car (id, make, model, price) values (564, 'Dodge', 'Ram Van 1500', '$5.62');
insert into car (id, make, model, price) values (565, 'BMW', 'Z4 M', '$6.54');
insert into car (id, make, model, price) values (566, 'Honda', 'Element', '$5.11');
insert into car (id, make, model, price) values (567, 'Saab', '9-3', '$9.89');
insert into car (id, make, model, price) values (568, 'Audi', '200', '$7.84');
insert into car (id, make, model, price) values (569, 'Chevrolet', 'APV', '$1.68');
insert into car (id, make, model, price) values (570, 'Pontiac', 'Bonneville', '$9.39');
insert into car (id, make, model, price) values (571, 'Isuzu', 'Hombre Space', '$6.50');
insert into car (id, make, model, price) values (572, 'Ford', 'Mustang', '$3.62');
insert into car (id, make, model, price) values (573, 'Mazda', 'CX-9', '$4.48');
insert into car (id, make, model, price) values (574, 'Cadillac', 'XLR', '$6.28');
insert into car (id, make, model, price) values (575, 'Volkswagen', 'Cabriolet', '$9.61');
insert into car (id, make, model, price) values (576, 'Nissan', 'Pathfinder', '$1.72');
insert into car (id, make, model, price) values (577, 'Volvo', 'S60', '$2.73');
insert into car (id, make, model, price) values (578, 'Chevrolet', 'Lumina', '$5.12');
insert into car (id, make, model, price) values (579, 'Chevrolet', 'Silverado 1500', '$8.64');
insert into car (id, make, model, price) values (580, 'Ford', 'Escort', '$0.72');
insert into car (id, make, model, price) values (581, 'Saturn', 'L-Series', '$0.03');
insert into car (id, make, model, price) values (582, 'GMC', '3500', '$6.78');
insert into car (id, make, model, price) values (583, 'Hyundai', 'Azera', '$2.30');
insert into car (id, make, model, price) values (584, 'Chevrolet', 'Silverado 2500', '$7.88');
insert into car (id, make, model, price) values (585, 'BMW', 'X6', '$6.16');
insert into car (id, make, model, price) values (586, 'Suzuki', 'Forenza', '$9.66');
insert into car (id, make, model, price) values (587, 'Nissan', 'Armada', '$2.19');
insert into car (id, make, model, price) values (588, 'Mitsubishi', 'Mighty Max', '$2.02');
insert into car (id, make, model, price) values (589, 'Jeep', 'Wrangler', '$3.60');
insert into car (id, make, model, price) values (590, 'Lincoln', 'Continental', '$6.04');
insert into car (id, make, model, price) values (591, 'Volvo', 'XC60', '$7.90');
insert into car (id, make, model, price) values (592, 'Ford', 'Laser', '$6.39');
insert into car (id, make, model, price) values (593, 'Nissan', '300ZX', '$3.71');
insert into car (id, make, model, price) values (594, 'Citroën', '2CV', '$3.73');
insert into car (id, make, model, price) values (595, 'Ford', 'Explorer Sport Trac', '$7.04');
insert into car (id, make, model, price) values (596, 'Mercedes-Benz', 'SL-Class', '$3.88');
insert into car (id, make, model, price) values (597, 'Aston Martin', 'DB9', '$2.23');
insert into car (id, make, model, price) values (598, 'Acura', 'NSX', '$4.10');
insert into car (id, make, model, price) values (599, 'Toyota', 'Tercel', '$4.10');
insert into car (id, make, model, price) values (600, 'Mitsubishi', 'Montero Sport', '$5.26');
insert into car (id, make, model, price) values (601, 'Buick', 'Reatta', '$0.01');
insert into car (id, make, model, price) values (602, 'Ford', 'F150', '$7.00');
insert into car (id, make, model, price) values (603, 'Chrysler', 'LeBaron', '$6.94');
insert into car (id, make, model, price) values (604, 'Cadillac', 'XLR', '$3.20');
insert into car (id, make, model, price) values (605, 'Lexus', 'IS', '$6.72');
insert into car (id, make, model, price) values (606, 'Volkswagen', 'Eurovan', '$4.75');
insert into car (id, make, model, price) values (607, 'Buick', 'Lucerne', '$5.93');
insert into car (id, make, model, price) values (608, 'Chevrolet', 'Camaro', '$6.61');
insert into car (id, make, model, price) values (609, 'Chevrolet', 'Sportvan G30', '$5.06');
insert into car (id, make, model, price) values (610, 'Rolls-Royce', 'Phantom', '$5.34');
insert into car (id, make, model, price) values (611, 'Buick', 'LeSabre', '$6.57');
insert into car (id, make, model, price) values (612, 'Hyundai', 'Tiburon', '$7.34');
insert into car (id, make, model, price) values (613, 'Dodge', 'Ram Van 1500', '$6.91');
insert into car (id, make, model, price) values (614, 'Nissan', 'Pathfinder', '$8.71');
insert into car (id, make, model, price) values (615, 'Suzuki', 'Kizashi', '$1.62');
insert into car (id, make, model, price) values (616, 'Toyota', 'Solara', '$5.29');
insert into car (id, make, model, price) values (617, 'Kia', 'Sportage', '$6.11');
insert into car (id, make, model, price) values (618, 'BMW', '5 Series', '$3.96');
insert into car (id, make, model, price) values (619, 'Volvo', 'V70', '$1.39');
insert into car (id, make, model, price) values (620, 'GMC', 'Savana 3500', '$2.74');
insert into car (id, make, model, price) values (621, 'Volkswagen', 'GLI', '$6.30');
insert into car (id, make, model, price) values (622, 'Jeep', 'Cherokee', '$0.16');
insert into car (id, make, model, price) values (623, 'Hyundai', 'Santa Fe', '$4.78');
insert into car (id, make, model, price) values (624, 'Suzuki', 'Kizashi', '$0.08');
insert into car (id, make, model, price) values (625, 'Chrysler', 'Sebring', '$2.29');
insert into car (id, make, model, price) values (626, 'Honda', 'Accord', '$3.17');
insert into car (id, make, model, price) values (627, 'Pontiac', 'Grand Prix', '$7.52');
insert into car (id, make, model, price) values (628, 'Acura', 'Legend', '$5.06');
insert into car (id, make, model, price) values (629, 'Jeep', 'Wrangler', '$4.42');
insert into car (id, make, model, price) values (630, 'Honda', 'Element', '$5.91');
insert into car (id, make, model, price) values (631, 'Honda', 'Ridgeline', '$9.87');
insert into car (id, make, model, price) values (632, 'Chevrolet', 'Monte Carlo', '$3.86');
insert into car (id, make, model, price) values (633, 'Lamborghini', 'Countach', '$5.47');
insert into car (id, make, model, price) values (634, 'Ford', 'F150', '$6.51');
insert into car (id, make, model, price) values (635, 'Dodge', 'Dakota', '$9.51');
insert into car (id, make, model, price) values (636, 'Mercury', 'Villager', '$5.45');
insert into car (id, make, model, price) values (637, 'Toyota', 'Paseo', '$0.27');
insert into car (id, make, model, price) values (638, 'Chevrolet', 'Camaro', '$9.56');
insert into car (id, make, model, price) values (639, 'Audi', 'A8', '$5.13');
insert into car (id, make, model, price) values (640, 'Mercury', 'Sable', '$8.20');
insert into car (id, make, model, price) values (641, 'Nissan', 'Xterra', '$9.65');
insert into car (id, make, model, price) values (642, 'Infiniti', 'M', '$8.88');
insert into car (id, make, model, price) values (643, 'Volvo', 'C30', '$3.21');
insert into car (id, make, model, price) values (644, 'Chevrolet', 'Express 3500', '$7.97');
insert into car (id, make, model, price) values (645, 'Mercedes-Benz', 'S-Class', '$7.86');
insert into car (id, make, model, price) values (646, 'Isuzu', 'Trooper', '$2.95');
insert into car (id, make, model, price) values (647, 'Nissan', 'Sentra', '$2.14');
insert into car (id, make, model, price) values (648, 'Mercury', 'Villager', '$3.02');
insert into car (id, make, model, price) values (649, 'Saab', '900', '$0.20');
insert into car (id, make, model, price) values (650, 'Ford', 'Fairlane', '$4.97');
insert into car (id, make, model, price) values (651, 'Dodge', 'Caravan', '$4.78');
insert into car (id, make, model, price) values (652, 'Honda', 'CR-V', '$0.16');
insert into car (id, make, model, price) values (653, 'Cadillac', 'XLR', '$3.50');
insert into car (id, make, model, price) values (654, 'Lexus', 'ES', '$8.38');
insert into car (id, make, model, price) values (655, 'GMC', 'Safari', '$9.09');
insert into car (id, make, model, price) values (656, 'Honda', 'Civic', '$1.49');
insert into car (id, make, model, price) values (657, 'Porsche', '911', '$0.62');
insert into car (id, make, model, price) values (658, 'Audi', 'S5', '$0.32');
insert into car (id, make, model, price) values (659, 'Ford', 'Festiva', '$1.00');
insert into car (id, make, model, price) values (660, 'Chevrolet', 'Suburban 1500', '$1.96');
insert into car (id, make, model, price) values (661, 'Saab', '9-3', '$9.36');
insert into car (id, make, model, price) values (662, 'Mazda', 'Mazda5', '$0.83');
insert into car (id, make, model, price) values (663, 'Hyundai', 'Tiburon', '$3.04');
insert into car (id, make, model, price) values (664, 'Volkswagen', 'Cabriolet', '$4.31');
insert into car (id, make, model, price) values (665, 'Infiniti', 'QX', '$7.51');
insert into car (id, make, model, price) values (666, 'Volkswagen', 'Passat', '$9.39');
insert into car (id, make, model, price) values (667, 'Saturn', 'Ion', '$4.14');
insert into car (id, make, model, price) values (668, 'Land Rover', 'LR3', '$4.38');
insert into car (id, make, model, price) values (669, 'Ford', 'Econoline E350', '$3.09');
insert into car (id, make, model, price) values (670, 'Infiniti', 'QX', '$9.12');
insert into car (id, make, model, price) values (671, 'Land Rover', 'Range Rover Evoque', '$7.61');
insert into car (id, make, model, price) values (672, 'Dodge', 'Dakota', '$1.24');
insert into car (id, make, model, price) values (673, 'Mitsubishi', 'Galant', '$4.54');
insert into car (id, make, model, price) values (674, 'Jaguar', 'XJ Series', '$9.09');
insert into car (id, make, model, price) values (675, 'Dodge', 'Aries', '$3.30');
insert into car (id, make, model, price) values (676, 'GMC', 'Sierra 3500', '$8.79');
insert into car (id, make, model, price) values (677, 'Mazda', 'Miata MX-5', '$1.48');
insert into car (id, make, model, price) values (678, 'Mazda', '929', '$7.68');
insert into car (id, make, model, price) values (679, 'Suzuki', 'Aerio', '$8.98');
insert into car (id, make, model, price) values (680, 'Audi', 'TT', '$3.86');
insert into car (id, make, model, price) values (681, 'Chevrolet', 'Corvette', '$9.88');
insert into car (id, make, model, price) values (682, 'Mercedes-Benz', 'SL-Class', '$1.84');
insert into car (id, make, model, price) values (683, 'MINI', 'Countryman', '$7.82');
insert into car (id, make, model, price) values (684, 'Nissan', 'Pathfinder', '$8.63');
insert into car (id, make, model, price) values (685, 'Dodge', 'Dakota', '$3.39');
insert into car (id, make, model, price) values (686, 'Cadillac', 'STS', '$7.01');
insert into car (id, make, model, price) values (687, 'Ford', 'F250', '$5.44');
insert into car (id, make, model, price) values (688, 'Chevrolet', 'Corvette', '$4.41');
insert into car (id, make, model, price) values (689, 'Mercury', 'Marquis', '$9.19');
insert into car (id, make, model, price) values (690, 'Lexus', 'IS F', '$6.37');
insert into car (id, make, model, price) values (691, 'Porsche', '911', '$8.85');
insert into car (id, make, model, price) values (692, 'Aston Martin', 'V8 Vantage', '$8.57');
insert into car (id, make, model, price) values (693, 'Buick', 'Electra', '$6.39');
insert into car (id, make, model, price) values (694, 'Dodge', 'Intrepid', '$6.52');
insert into car (id, make, model, price) values (695, 'Mitsubishi', 'Challenger', '$6.72');
insert into car (id, make, model, price) values (696, 'Ferrari', 'FF', '$1.04');
insert into car (id, make, model, price) values (697, 'Porsche', '928', '$0.81');
insert into car (id, make, model, price) values (698, 'Porsche', '911', '$9.43');
insert into car (id, make, model, price) values (699, 'Toyota', 'T100 Xtra', '$4.13');
insert into car (id, make, model, price) values (700, 'Chevrolet', 'Express 1500', '$8.90');
insert into car (id, make, model, price) values (701, 'Ford', 'Taurus X', '$3.34');
insert into car (id, make, model, price) values (702, 'Isuzu', 'Rodeo', '$6.31');
insert into car (id, make, model, price) values (703, 'Ford', 'Explorer', '$4.90');
insert into car (id, make, model, price) values (704, 'Acura', 'TL', '$7.81');
insert into car (id, make, model, price) values (705, 'Audi', 'A4', '$7.47');
insert into car (id, make, model, price) values (706, 'Plymouth', 'Prowler', '$0.19');
insert into car (id, make, model, price) values (707, 'Lincoln', 'Blackwood', '$9.23');
insert into car (id, make, model, price) values (708, 'Volkswagen', 'GTI', '$8.60');
insert into car (id, make, model, price) values (709, 'Acura', 'CL', '$3.58');
insert into car (id, make, model, price) values (710, 'Pontiac', 'Firebird', '$1.38');
insert into car (id, make, model, price) values (711, 'BMW', 'X3', '$6.66');
insert into car (id, make, model, price) values (712, 'MINI', 'Cooper Clubman', '$6.45');
insert into car (id, make, model, price) values (713, 'Chevrolet', 'Cruze', '$9.29');
insert into car (id, make, model, price) values (714, 'Suzuki', 'Daewoo Magnus', '$1.82');
insert into car (id, make, model, price) values (715, 'Suzuki', 'SX4', '$3.39');
insert into car (id, make, model, price) values (716, 'MINI', 'Cooper', '$7.94');
insert into car (id, make, model, price) values (717, 'Kia', 'Sedona', '$2.41');
insert into car (id, make, model, price) values (718, 'Chrysler', 'Town & Country', '$3.48');
insert into car (id, make, model, price) values (719, 'Land Rover', 'Defender', '$0.31');
insert into car (id, make, model, price) values (720, 'Renault', 'Alliance', '$0.65');
insert into car (id, make, model, price) values (721, 'Ford', 'Festiva', '$1.83');
insert into car (id, make, model, price) values (722, 'Cadillac', 'Escalade EXT', '$7.96');
insert into car (id, make, model, price) values (723, 'Toyota', 'Tacoma Xtra', '$1.06');
insert into car (id, make, model, price) values (724, 'Mercedes-Benz', 'SL65 AMG', '$0.97');
insert into car (id, make, model, price) values (725, 'Hyundai', 'Sonata', '$0.41');
insert into car (id, make, model, price) values (726, 'Mitsubishi', '3000GT', '$1.81');
insert into car (id, make, model, price) values (727, 'Honda', 'Crosstour', '$8.52');
insert into car (id, make, model, price) values (728, 'Kia', 'Optima', '$0.85');
insert into car (id, make, model, price) values (729, 'Dodge', 'Dakota', '$6.15');
insert into car (id, make, model, price) values (730, 'Pontiac', 'Trans Sport', '$5.73');
insert into car (id, make, model, price) values (731, 'Lexus', 'LS', '$8.27');
insert into car (id, make, model, price) values (732, 'Kia', 'Amanti', '$2.50');
insert into car (id, make, model, price) values (733, 'Audi', 'A6', '$5.80');
insert into car (id, make, model, price) values (734, 'Toyota', 'Yaris', '$3.63');
insert into car (id, make, model, price) values (735, 'Porsche', '911', '$7.13');
insert into car (id, make, model, price) values (736, 'Isuzu', 'Rodeo Sport', '$4.40');
insert into car (id, make, model, price) values (737, 'Saturn', 'S-Series', '$8.42');
insert into car (id, make, model, price) values (738, 'Chevrolet', 'Corvette', '$3.36');
insert into car (id, make, model, price) values (739, 'Lincoln', 'Town Car', '$6.41');
insert into car (id, make, model, price) values (740, 'Acura', 'CL', '$8.38');
insert into car (id, make, model, price) values (741, 'Infiniti', 'G', '$9.30');
insert into car (id, make, model, price) values (742, 'Subaru', 'Impreza', '$6.92');
insert into car (id, make, model, price) values (743, 'Suzuki', 'Swift', '$1.27');
insert into car (id, make, model, price) values (744, 'Mazda', 'CX-7', '$0.97');
insert into car (id, make, model, price) values (745, 'Nissan', 'Cube', '$3.45');
insert into car (id, make, model, price) values (746, 'Mercedes-Benz', 'R-Class', '$1.17');
insert into car (id, make, model, price) values (747, 'Hummer', 'H2 SUV', '$8.71');
insert into car (id, make, model, price) values (748, 'Honda', 'Pilot', '$9.87');
insert into car (id, make, model, price) values (749, 'Nissan', 'Pathfinder', '$4.29');
insert into car (id, make, model, price) values (750, 'Chevrolet', 'Corvette', '$3.85');
insert into car (id, make, model, price) values (751, 'Rolls-Royce', 'Phantom', '$1.04');
insert into car (id, make, model, price) values (752, 'Pontiac', 'Fiero', '$7.05');
insert into car (id, make, model, price) values (753, 'Ford', 'Crown Victoria', '$3.39');
insert into car (id, make, model, price) values (754, 'Kia', 'Rio', '$9.11');
insert into car (id, make, model, price) values (755, 'Nissan', 'Versa', '$3.99');
insert into car (id, make, model, price) values (756, 'BMW', 'X5', '$3.40');
insert into car (id, make, model, price) values (757, 'Hyundai', 'Elantra', '$1.27');
insert into car (id, make, model, price) values (758, 'Honda', 'Passport', '$1.78');
insert into car (id, make, model, price) values (759, 'Mercury', 'Topaz', '$9.29');
insert into car (id, make, model, price) values (760, 'Audi', 'S5', '$8.10');
insert into car (id, make, model, price) values (761, 'Saturn', 'L-Series', '$4.20');
insert into car (id, make, model, price) values (762, 'Kia', 'Spectra5', '$9.10');
insert into car (id, make, model, price) values (763, 'BMW', 'M3', '$8.64');
insert into car (id, make, model, price) values (764, 'Toyota', 'Venza', '$9.15');
insert into car (id, make, model, price) values (765, 'Lincoln', 'MKT', '$4.75');
insert into car (id, make, model, price) values (766, 'Mercury', 'Grand Marquis', '$9.17');
insert into car (id, make, model, price) values (767, 'Kia', 'Sportage', '$9.15');
insert into car (id, make, model, price) values (768, 'Mazda', 'Mazda6', '$0.32');
insert into car (id, make, model, price) values (769, 'Lotus', 'Esprit', '$6.34');
insert into car (id, make, model, price) values (770, 'Plymouth', 'Neon', '$0.73');
insert into car (id, make, model, price) values (771, 'Dodge', 'D150', '$6.96');
insert into car (id, make, model, price) values (772, 'Pontiac', 'Firebird', '$6.17');
insert into car (id, make, model, price) values (773, 'Ford', 'Aspire', '$0.93');
insert into car (id, make, model, price) values (774, 'Mazda', '626', '$3.03');
insert into car (id, make, model, price) values (775, 'Pontiac', 'GTO', '$7.80');
insert into car (id, make, model, price) values (776, 'Chevrolet', 'Corsica', '$9.49');
insert into car (id, make, model, price) values (777, 'Land Rover', 'Range Rover Sport', '$3.70');
insert into car (id, make, model, price) values (778, 'Ford', 'Thunderbird', '$9.33');
insert into car (id, make, model, price) values (779, 'Toyota', 'Celica', '$8.22');
insert into car (id, make, model, price) values (780, 'Porsche', 'Cayman', '$3.70');
insert into car (id, make, model, price) values (781, 'Volvo', 'S80', '$9.35');
insert into car (id, make, model, price) values (782, 'Volkswagen', 'Jetta', '$7.11');
insert into car (id, make, model, price) values (783, 'GMC', 'Terrain', '$2.02');
insert into car (id, make, model, price) values (784, 'Pontiac', 'G6', '$1.52');
insert into car (id, make, model, price) values (785, 'Dodge', 'Charger', '$0.15');
insert into car (id, make, model, price) values (786, 'BMW', '6 Series', '$1.42');
insert into car (id, make, model, price) values (787, 'Audi', 'S8', '$2.91');
insert into car (id, make, model, price) values (788, 'Land Rover', 'Defender 90', '$5.05');
insert into car (id, make, model, price) values (789, 'Cadillac', 'Escalade EXT', '$9.16');
insert into car (id, make, model, price) values (790, 'Chevrolet', 'Sportvan G30', '$8.35');
insert into car (id, make, model, price) values (791, 'Maybach', 'Landaulet', '$6.64');
insert into car (id, make, model, price) values (792, 'Mercury', 'Mystique', '$3.46');
insert into car (id, make, model, price) values (793, 'Ford', 'F150', '$0.88');
insert into car (id, make, model, price) values (794, 'Mercedes-Benz', '190E', '$2.32');
insert into car (id, make, model, price) values (795, 'Hyundai', 'Genesis', '$4.53');
insert into car (id, make, model, price) values (796, 'GMC', 'Yukon', '$3.97');
insert into car (id, make, model, price) values (797, 'Hyundai', 'Elantra', '$2.43');
insert into car (id, make, model, price) values (798, 'Volkswagen', 'GTI', '$4.05');
insert into car (id, make, model, price) values (799, 'Jeep', 'Wrangler', '$8.86');
insert into car (id, make, model, price) values (800, 'Nissan', 'Sentra', '$9.09');
insert into car (id, make, model, price) values (801, 'Mitsubishi', 'Galant', '$5.54');
insert into car (id, make, model, price) values (802, 'Mazda', 'Familia', '$3.73');
insert into car (id, make, model, price) values (803, 'Audi', 'TT', '$2.66');
insert into car (id, make, model, price) values (804, 'Porsche', '911', '$7.88');
insert into car (id, make, model, price) values (805, 'Mitsubishi', 'Galant', '$4.12');
insert into car (id, make, model, price) values (806, 'Plymouth', 'Voyager', '$8.08');
insert into car (id, make, model, price) values (807, 'Mercury', 'Tracer', '$6.32');
insert into car (id, make, model, price) values (808, 'Scion', 'tC', '$2.65');
insert into car (id, make, model, price) values (809, 'Acura', 'TSX', '$4.33');
insert into car (id, make, model, price) values (810, 'Suzuki', 'Swift', '$0.77');
insert into car (id, make, model, price) values (811, 'Toyota', 'Tacoma', '$4.49');
insert into car (id, make, model, price) values (812, 'Volkswagen', 'GTI', '$7.01');
insert into car (id, make, model, price) values (813, 'Daewoo', 'Lanos', '$3.83');
insert into car (id, make, model, price) values (814, 'Dodge', 'Ram 3500', '$5.63');
insert into car (id, make, model, price) values (815, 'Audi', 'S8', '$4.96');
insert into car (id, make, model, price) values (816, 'Hyundai', 'Genesis', '$7.51');
insert into car (id, make, model, price) values (817, 'Pontiac', 'Firebird', '$9.87');
insert into car (id, make, model, price) values (818, 'Chevrolet', 'Express', '$9.76');
insert into car (id, make, model, price) values (819, 'Mercedes-Benz', 'S-Class', '$8.64');
insert into car (id, make, model, price) values (820, 'Dodge', 'Intrepid', '$8.31');
insert into car (id, make, model, price) values (821, 'Volkswagen', 'Passat', '$4.67');
insert into car (id, make, model, price) values (822, 'Nissan', 'Versa', '$4.43');
insert into car (id, make, model, price) values (823, 'Dodge', 'Ram Van 3500', '$0.31');
insert into car (id, make, model, price) values (824, 'BMW', 'X6', '$1.67');
insert into car (id, make, model, price) values (825, 'Dodge', 'Grand Caravan', '$5.25');
insert into car (id, make, model, price) values (826, 'Nissan', 'Quest', '$0.70');
insert into car (id, make, model, price) values (827, 'Dodge', 'Ram Wagon B250', '$2.36');
insert into car (id, make, model, price) values (828, 'Pontiac', 'Grand Am', '$4.57');
insert into car (id, make, model, price) values (829, 'Toyota', 'Camry', '$2.12');
insert into car (id, make, model, price) values (830, 'Subaru', 'Baja', '$9.82');
insert into car (id, make, model, price) values (831, 'Lincoln', 'LS', '$1.01');
insert into car (id, make, model, price) values (832, 'Buick', 'LeSabre', '$9.77');
insert into car (id, make, model, price) values (833, 'Infiniti', 'I', '$8.74');
insert into car (id, make, model, price) values (834, 'Ford', 'Thunderbird', '$0.81');
insert into car (id, make, model, price) values (835, 'Mazda', 'RX-8', '$8.27');
insert into car (id, make, model, price) values (836, 'Ford', 'F250', '$1.15');
insert into car (id, make, model, price) values (837, 'Porsche', '911', '$4.55');
insert into car (id, make, model, price) values (838, 'Cadillac', 'Eldorado', '$3.47');
insert into car (id, make, model, price) values (839, 'Lexus', 'GX', '$8.69');
insert into car (id, make, model, price) values (840, 'Dodge', 'Intrepid', '$4.09');
insert into car (id, make, model, price) values (841, 'BMW', '5 Series', '$6.83');
insert into car (id, make, model, price) values (842, 'Infiniti', 'G', '$3.37');
insert into car (id, make, model, price) values (843, 'Dodge', 'Ram', '$2.30');
insert into car (id, make, model, price) values (844, 'BMW', '5 Series', '$1.90');
insert into car (id, make, model, price) values (845, 'Lincoln', 'Town Car', '$2.78');
insert into car (id, make, model, price) values (846, 'Infiniti', 'J', '$9.86');
insert into car (id, make, model, price) values (847, 'Hyundai', 'Tiburon', '$9.05');
insert into car (id, make, model, price) values (848, 'Buick', 'LeSabre', '$6.91');
insert into car (id, make, model, price) values (849, 'Volvo', 'C70', '$0.64');
insert into car (id, make, model, price) values (850, 'Suzuki', 'Sidekick', '$9.57');
insert into car (id, make, model, price) values (851, 'Mercury', 'Mariner', '$6.33');
insert into car (id, make, model, price) values (852, 'Chrysler', 'Sebring', '$0.68');
insert into car (id, make, model, price) values (853, 'Ford', 'Transit Connect', '$2.33');
insert into car (id, make, model, price) values (854, 'GMC', 'Envoy', '$3.89');
insert into car (id, make, model, price) values (855, 'Subaru', 'Legacy', '$3.21');
insert into car (id, make, model, price) values (856, 'Hyundai', 'Accent', '$4.35');
insert into car (id, make, model, price) values (857, 'Lexus', 'LX', '$5.81');
insert into car (id, make, model, price) values (858, 'Acura', 'RL', '$8.42');
insert into car (id, make, model, price) values (859, 'Subaru', 'Impreza', '$5.22');
insert into car (id, make, model, price) values (860, 'Lincoln', 'MKX', '$7.44');
insert into car (id, make, model, price) values (861, 'Dodge', 'Ram 2500', '$2.11');
insert into car (id, make, model, price) values (862, 'Audi', 'S4', '$8.75');
insert into car (id, make, model, price) values (863, 'Aston Martin', 'DB9', '$2.10');
insert into car (id, make, model, price) values (864, 'Mercury', 'Sable', '$7.48');
insert into car (id, make, model, price) values (865, 'Nissan', 'Frontier', '$6.64');
insert into car (id, make, model, price) values (866, 'Suzuki', 'Swift', '$4.45');
insert into car (id, make, model, price) values (867, 'Audi', 'A6', '$3.99');
insert into car (id, make, model, price) values (868, 'Ford', 'Thunderbird', '$9.62');
insert into car (id, make, model, price) values (869, 'Toyota', 'Prius', '$2.00');
insert into car (id, make, model, price) values (870, 'Lexus', 'LS', '$6.28');
insert into car (id, make, model, price) values (871, 'Ford', 'F-Series Super Duty', '$3.50');
insert into car (id, make, model, price) values (872, 'Mazda', 'Protege5', '$7.73');
insert into car (id, make, model, price) values (873, 'Smart', 'Fortwo', '$9.16');
insert into car (id, make, model, price) values (874, 'Chevrolet', 'Express 3500', '$1.16');
insert into car (id, make, model, price) values (875, 'Mercedes-Benz', 'SL-Class', '$0.41');
insert into car (id, make, model, price) values (876, 'Buick', 'Century', '$0.89');
insert into car (id, make, model, price) values (877, 'Bentley', 'Continental', '$4.68');
insert into car (id, make, model, price) values (878, 'Volkswagen', 'Golf', '$1.41');
insert into car (id, make, model, price) values (879, 'Subaru', 'Loyale', '$7.20');
insert into car (id, make, model, price) values (880, 'Toyota', 'Matrix', '$6.30');
insert into car (id, make, model, price) values (881, 'Audi', 'S4', '$0.91');
insert into car (id, make, model, price) values (882, 'Ford', 'Flex', '$2.48');
insert into car (id, make, model, price) values (883, 'Mitsubishi', 'Eclipse', '$9.47');
insert into car (id, make, model, price) values (884, 'Nissan', 'Altima', '$9.49');
insert into car (id, make, model, price) values (885, 'Volkswagen', 'Golf', '$4.16');
insert into car (id, make, model, price) values (886, 'Mitsubishi', 'Mirage', '$8.68');
insert into car (id, make, model, price) values (887, 'Volvo', 'S40', '$6.29');
insert into car (id, make, model, price) values (888, 'Volvo', 'V70', '$5.44');
insert into car (id, make, model, price) values (889, 'Mercury', 'Mariner', '$4.03');
insert into car (id, make, model, price) values (890, 'Nissan', '350Z', '$8.77');
insert into car (id, make, model, price) values (891, 'Dodge', 'Ram 2500', '$0.61');
insert into car (id, make, model, price) values (892, 'Mazda', 'B-Series', '$0.92');
insert into car (id, make, model, price) values (893, 'Chevrolet', 'Impala', '$6.36');
insert into car (id, make, model, price) values (894, 'Oldsmobile', 'Achieva', '$4.79');
insert into car (id, make, model, price) values (895, 'Acura', 'CL', '$4.31');
insert into car (id, make, model, price) values (896, 'Dodge', 'Ram 1500', '$5.64');
insert into car (id, make, model, price) values (897, 'Honda', 'Civic', '$5.31');
insert into car (id, make, model, price) values (898, 'Chevrolet', 'Astro', '$1.55');
insert into car (id, make, model, price) values (899, 'Dodge', 'Ram 2500 Club', '$3.32');
insert into car (id, make, model, price) values (900, 'Toyota', 'RAV4', '$9.86');
insert into car (id, make, model, price) values (901, 'GMC', 'Canyon', '$2.10');
insert into car (id, make, model, price) values (902, 'Mazda', '626', '$5.19');
insert into car (id, make, model, price) values (903, 'Land Rover', 'LR4', '$5.67');
insert into car (id, make, model, price) values (904, 'Dodge', 'Dakota', '$9.01');
insert into car (id, make, model, price) values (905, 'Lexus', 'LFA', '$6.59');
insert into car (id, make, model, price) values (906, 'Ford', 'EXP', '$2.99');
insert into car (id, make, model, price) values (907, 'Dodge', 'Grand Caravan', '$1.08');
insert into car (id, make, model, price) values (908, 'Chevrolet', 'Sportvan G20', '$7.01');
insert into car (id, make, model, price) values (909, 'Buick', 'LeSabre', '$1.64');
insert into car (id, make, model, price) values (910, 'Mercury', 'Mountaineer', '$5.90');
insert into car (id, make, model, price) values (911, 'Subaru', 'SVX', '$7.33');
insert into car (id, make, model, price) values (912, 'Eagle', 'Summit', '$9.91');
insert into car (id, make, model, price) values (913, 'Dodge', 'Viper', '$6.44');
insert into car (id, make, model, price) values (914, 'Porsche', '928', '$3.92');
insert into car (id, make, model, price) values (915, 'Buick', 'Park Avenue', '$2.52');
insert into car (id, make, model, price) values (916, 'Chrysler', 'LeBaron', '$6.92');
insert into car (id, make, model, price) values (917, 'Honda', 'Accord', '$2.94');
insert into car (id, make, model, price) values (918, 'Aston Martin', 'Vantage', '$6.08');
insert into car (id, make, model, price) values (919, 'Ford', 'Mustang', '$2.13');
insert into car (id, make, model, price) values (920, 'Mercedes-Benz', 'SL-Class', '$3.86');
insert into car (id, make, model, price) values (921, 'Volkswagen', 'Golf', '$7.67');
insert into car (id, make, model, price) values (922, 'Ford', 'Thunderbird', '$8.30');
insert into car (id, make, model, price) values (923, 'Kia', 'Sportage', '$7.60');
insert into car (id, make, model, price) values (924, 'Toyota', 'TundraMax', '$9.57');
insert into car (id, make, model, price) values (925, 'Nissan', 'Pathfinder', '$4.46');
insert into car (id, make, model, price) values (926, 'Ford', 'Edge', '$3.01');
insert into car (id, make, model, price) values (927, 'Dodge', 'Stratus', '$5.82');
insert into car (id, make, model, price) values (928, 'Chevrolet', 'Metro', '$5.73');
insert into car (id, make, model, price) values (929, 'Porsche', 'Panamera', '$8.87');
insert into car (id, make, model, price) values (930, 'Isuzu', 'Space', '$5.15');
insert into car (id, make, model, price) values (931, 'Hummer', 'H3', '$8.41');
insert into car (id, make, model, price) values (932, 'Toyota', 'Tacoma', '$8.05');
insert into car (id, make, model, price) values (933, 'Mitsubishi', 'Mirage', '$3.26');
insert into car (id, make, model, price) values (934, 'Mitsubishi', 'Eclipse', '$3.53');
insert into car (id, make, model, price) values (935, 'Mazda', 'MPV', '$9.38');
insert into car (id, make, model, price) values (936, 'Jeep', 'Wrangler', '$4.53');
insert into car (id, make, model, price) values (937, 'Jeep', 'Liberty', '$3.52');
insert into car (id, make, model, price) values (938, 'Land Rover', 'LR2', '$9.67');
insert into car (id, make, model, price) values (939, 'Audi', 'A6', '$5.12');
insert into car (id, make, model, price) values (940, 'Chevrolet', 'Monte Carlo', '$6.69');
insert into car (id, make, model, price) values (941, 'Dodge', 'Durango', '$3.27');
insert into car (id, make, model, price) values (942, 'Acura', 'CL', '$2.45');
insert into car (id, make, model, price) values (943, 'Pontiac', '6000', '$6.79');
insert into car (id, make, model, price) values (944, 'Ford', 'F250', '$9.55');
insert into car (id, make, model, price) values (945, 'Kia', 'Optima', '$4.85');
insert into car (id, make, model, price) values (946, 'Mitsubishi', 'Chariot', '$0.37');
insert into car (id, make, model, price) values (947, 'Audi', 'R8', '$5.98');
insert into car (id, make, model, price) values (948, 'Mazda', 'Miata MX-5', '$8.35');
insert into car (id, make, model, price) values (949, 'Mercury', 'Mountaineer', '$1.23');
insert into car (id, make, model, price) values (950, 'Ford', 'Edge', '$7.64');
insert into car (id, make, model, price) values (951, 'Ford', 'Escort', '$4.80');
insert into car (id, make, model, price) values (952, 'Ford', 'Taurus', '$1.20');
insert into car (id, make, model, price) values (953, 'Audi', 'A6', '$7.01');
insert into car (id, make, model, price) values (954, 'Chevrolet', 'Express 3500', '$6.99');
insert into car (id, make, model, price) values (955, 'Ford', 'Crown Victoria', '$1.21');
insert into car (id, make, model, price) values (956, 'Lincoln', 'Continental', '$0.57');
insert into car (id, make, model, price) values (957, 'Mazda', 'Miata MX-5', '$8.46');
insert into car (id, make, model, price) values (958, 'Buick', 'LaCrosse', '$3.88');
insert into car (id, make, model, price) values (959, 'Chevrolet', 'Corvette', '$6.23');
insert into car (id, make, model, price) values (960, 'Ford', 'Flex', '$9.86');
insert into car (id, make, model, price) values (961, 'Ford', 'Econoline E350', '$5.51');
insert into car (id, make, model, price) values (962, 'Toyota', 'Supra', '$3.98');
insert into car (id, make, model, price) values (963, 'Honda', 'S2000', '$4.46');
insert into car (id, make, model, price) values (964, 'Lotus', 'Elise', '$0.81');
insert into car (id, make, model, price) values (965, 'Volkswagen', 'GTI', '$0.41');
insert into car (id, make, model, price) values (966, 'Nissan', 'Xterra', '$4.08');
insert into car (id, make, model, price) values (967, 'Maserati', 'Coupe', '$8.91');
insert into car (id, make, model, price) values (968, 'Ford', 'F250', '$9.48');
insert into car (id, make, model, price) values (969, 'Ford', 'Probe', '$0.18');
insert into car (id, make, model, price) values (970, 'Audi', 'A5', '$8.62');
insert into car (id, make, model, price) values (971, 'Mercury', 'Mariner', '$8.59');
insert into car (id, make, model, price) values (972, 'Volvo', 'C70', '$4.35');
insert into car (id, make, model, price) values (973, 'Isuzu', 'Hombre', '$6.94');
insert into car (id, make, model, price) values (974, 'GMC', 'Savana 3500', '$9.70');
insert into car (id, make, model, price) values (975, 'Subaru', 'Legacy', '$7.55');
insert into car (id, make, model, price) values (976, 'Chrysler', 'Sebring', '$7.20');
insert into car (id, make, model, price) values (977, 'Chevrolet', 'Silverado 3500', '$9.78');
insert into car (id, make, model, price) values (978, 'Toyota', 'T100', '$6.08');
insert into car (id, make, model, price) values (979, 'Mercedes-Benz', '400SEL', '$8.24');
insert into car (id, make, model, price) values (980, 'Toyota', 'RAV4', '$7.48');
insert into car (id, make, model, price) values (981, 'Subaru', 'Impreza', '$8.27');
insert into car (id, make, model, price) values (982, 'GMC', 'Savana', '$1.52');
insert into car (id, make, model, price) values (983, 'GMC', 'Sierra Hybrid', '$3.94');
insert into car (id, make, model, price) values (984, 'Cadillac', 'Escalade ESV', '$0.84');
insert into car (id, make, model, price) values (985, 'Audi', 'Q7', '$0.18');
insert into car (id, make, model, price) values (986, 'GMC', 'Envoy', '$1.44');
insert into car (id, make, model, price) values (987, 'Shelby', 'GT350', '$7.02');
insert into car (id, make, model, price) values (988, 'Chevrolet', 'Express 3500', '$1.54');
insert into car (id, make, model, price) values (989, 'Ford', 'Escape', '$4.62');
insert into car (id, make, model, price) values (990, 'Chevrolet', 'Camaro', '$5.74');
insert into car (id, make, model, price) values (991, 'Ford', 'Flex', '$1.92');
insert into car (id, make, model, price) values (992, 'Honda', 'CR-V', '$6.89');
insert into car (id, make, model, price) values (993, 'Saturn', 'Outlook', '$7.42');
insert into car (id, make, model, price) values (994, 'Lexus', 'LX', '$0.82');
insert into car (id, make, model, price) values (995, 'Pontiac', 'Sunfire', '$1.95');
insert into car (id, make, model, price) values (996, 'Oldsmobile', 'Silhouette', '$0.47');
insert into car (id, make, model, price) values (997, 'Toyota', 'Sequoia', '$2.26');
insert into car (id, make, model, price) values (998, 'Buick', 'Regal', '$7.33');
insert into car (id, make, model, price) values (999, 'Chevrolet', 'Camaro', '$6.68');
insert into car (id, make, model, price) values (1000, 'Toyota', 'Tundra', '$6.08');
